import { EnumAuthStatusCodeError } from "../auth";
import { EnumInternalStatusCodeError } from "../error";
import { EnumRequestStatusCodeError } from "../request";
import { EnumUserStatusCodeError } from "../user";
export declare const ErrorStatusCodeMap: {
    [x: number]: string;
    UserNotFoundError: EnumUserStatusCodeError.UserNotFoundError;
    UserExistsError: EnumUserStatusCodeError.UserExistsError;
    UserInactiveError: EnumUserStatusCodeError.UserInactiveError;
    UserEmailExistsError: EnumUserStatusCodeError.UserEmailExistsError;
    UserSignUpLinkNotFound: EnumUserStatusCodeError.UserSignUpLinkNotFound;
    UserSignUpLinkExpired: EnumUserStatusCodeError.UserSignUpLinkExpired;
    UserVerifiedOnlyError: EnumUserStatusCodeError.UserVerifiedOnlyError;
    AuthInvalidEmailError: EnumAuthStatusCodeError.AuthInvalidEmailError;
    AuthWrongCredentialsError: EnumAuthStatusCodeError.AuthWrongCredentialsError;
    AuthBadRequestError: EnumAuthStatusCodeError.AuthBadRequestError;
    AuthGuardJwtAccessTokenError: EnumAuthStatusCodeError.AuthGuardJwtAccessTokenError;
    AuthGuardJwtAccessTokenExpiredError: EnumAuthStatusCodeError.AuthGuardJwtAccessTokenExpiredError;
    AuthGuardJwtRefreshTokenError: EnumAuthStatusCodeError.AuthGuardJwtRefreshTokenError;
    AuthGuardPasswordExpiredError: EnumAuthStatusCodeError.AuthGuardPasswordExpiredError;
    AuthPasswordExpiredError: EnumAuthStatusCodeError.AuthPasswordExpiredError;
    AuthPasswordNotMatchError: EnumAuthStatusCodeError.AuthPasswordNotMatchError;
    AuthPasswordNewMustDifferenceError: EnumAuthStatusCodeError.AuthPasswordNewMustDifferenceError;
    AuthResetPasswordLinkExpired: EnumAuthStatusCodeError.AuthResetPasswordLinkExpired;
    AuthEmailExist: EnumAuthStatusCodeError.AuthEmailExist;
    AuthUsernameExist: EnumAuthStatusCodeError.AuthUsernameExist;
    GlobalError: EnumInternalStatusCodeError.GlobalError;
    TypeError: EnumInternalStatusCodeError.TypeError;
    TypeOrmError: EnumInternalStatusCodeError.TypeOrmError;
    UnknownError: EnumInternalStatusCodeError.UnknownError;
    ServiceUnavailable: EnumInternalStatusCodeError.ServiceUnavailable;
    RequestTimeout: EnumInternalStatusCodeError.RequestTimeout;
    RequestValidationError: EnumRequestStatusCodeError.RequestValidationError;
    RequestTimestampInvalidError: EnumRequestStatusCodeError.RequestTimestampInvalidError;
    RequestUserAgentInvalidError: EnumRequestStatusCodeError.RequestUserAgentInvalidError;
    RequestPreconditionFailedError: EnumRequestStatusCodeError.RequestPreconditionFailedError;
};
export type ErrorStatusCodeType = keyof typeof ErrorStatusCodeMap;
